### ISSUE TITLE
Use versioning on sequence feature annotation

### ISSUE THREAD

**Issue by jakebeal** [SD2E/SYNBICT#11]
After running the sequence feature annotation, rather than replacing the old instance, this seems like a very good place to use versioning and persistent identities.

**Comment by jakebeal** [comment]
Implemented. Needs a test to verify that this works correctly when run on other than version 1.

**Comment by nroehner** [comment]
Required some additional modification and rethinking of how we copy ComponentDefinitions to be annotated. The way this works now is that ComponentDefinitions already in the annotation namespace have the version of their copy incremented if possible, while ComponentDefinitions not in the annotation namespace have their copy imported into the annotation namespace with version 1. This is completed as of f71bdfd8c936077c099b0f6bb330a90f40b4fee5.
