### ISSUE TITLE
Accept GenBank/FASTA inputs

### ISSUE THREAD

**Issue by jakebeal** [SD2E/SYNBICT#27]
We can allow inputs in other formats like GenBank, GFF, and FASTA, which will then be automatically converted, making it easier for others to use this besides SBOL folks.

**Comment by jakebeal** [comment]
Splitting the GFF, which will be more difficult, out into its own issue #34

**Comment by nroehner** [comment]
Completed. A file's format is inferred from it's extension and it is converted with a call to the online SBOL validator/converter if is GenBank or FASTA.
